name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: gradle
      - run: ./gradlew build --no-daemon
      - run: ./gradlew jacocoTestReport --no-daemon
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/tests/test
            **/build/reports/jacoco/test/html
